### ISSUE TITLE
Wrong file type crashes server.

### ISSUE THREAD

**Issue by OUeasley** [GuilleOsores/cribl_challenge#5]
Given this command:

`curl -F 'file=@/Users/bryceeasley/Downloads/out.zip' http://localhost:8090/uploadFile -X POST  -v`

The application is crashing with:

```Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_http_outgoing.js:668:15)
    at ServerResponse.end (_http_outgoing.js:788:7)
    at ChunksProcesor.<anonymous> (/Users/bryceeasley/WebstormProjects/cribl_challenge/src/handlers/file.ts:236:21)
    at Generator.next (<anonymous>)
    at /Users/bryceeasley/WebstormProjects/cribl_challenge/src/handlers/file.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/bryceeasley/WebstormProjects/cribl_challenge/src/handlers/file.ts:4:12)
    at ChunksProcesor.close (/Users/bryceeasley/WebstormProjects/cribl_challenge/src/handlers/file.ts:243:16)
    at ChunksProcesor.<anonymous> (/Users/bryceeasley/WebstormProjects/cribl_challenge/src/handlers/file.ts:146:20)
    at Generator.next (<anonymous>)```

**Comment by GuilleOsores** [comment]
it was weird, I couldn't reproduce the error, but I saw I was writing the response multiple times. So I guess this changes will fix it.
